version: '3.9'
services:
  api-python3.6:
    image: flask_redis_image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - "${PWD}:/opt/app"
    networks:
      - my-network

networks:
  my-network:
